namespace Alloyed.DevOps.Multitool.Core.Catalog.Services;

using Alloyed.DevOps.Multitool.Core.Catalog.Contracts;
using Alloyed.DevOps.Multitool.Core.Catalog.Models;

public sealed class InMemoryWrapperCatalog : IWrapperCatalog
{
    private const string WrapperModuleName = "Alloyed.DevOps.Multitool";

    private static readonly IReadOnlyDictionary<string, string> WrapperMap =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            // <auto-generated:wrapper-map>
            ["Clear-Host"] = "Clear-AlloyedHost",
            ["clear"] = "Clear-AlloyedHost",
            ["cls"] = "Clear-AlloyedHost",
            ["Compress-Archive"] = "Compress-AlloyedArchive",
            ["ConvertFrom-Json"] = "ConvertFrom-AlloyedJson",
            ["ConvertFrom-SecureString"] = "ConvertFrom-AlloyedSecureString",
            ["ConvertTo-Json"] = "ConvertTo-AlloyedJson",
            ["ConvertTo-SecureString"] = "ConvertTo-AlloyedSecureString",
            ["ConvertTo-Xml"] = "ConvertTo-AlloyedXml",
            ["Copy-Item"] = "Copy-AlloyedItem",
            ["copy"] = "Copy-AlloyedItem",
            ["cp"] = "Copy-AlloyedItem",
            ["Expand-Archive"] = "Expand-AlloyedArchive",
            ["Export-PfxCertificate"] = "Export-AlloyedPfxCertificate",
            ["Get-Acl"] = "Get-AlloyedAcl",
            ["Get-AuthenticodeSignature"] = "Get-AlloyedAuthenticodeSignature",
            ["Get-ChildItem"] = "Get-AlloyedChildItem",
            ["gci"] = "Get-AlloyedChildItem",
            ["Get-Content"] = "Get-AlloyedContent",
            ["gc"] = "Get-AlloyedContent",
            ["Get-Credential"] = "Get-AlloyedCredential",
            ["Get-Item"] = "Get-AlloyedItem",
            ["gi"] = "Get-AlloyedItem",
            ["Get-Location"] = "Get-AlloyedLocation",
            ["gl"] = "Get-AlloyedLocation",
            ["pwd"] = "Get-AlloyedLocation",
            ["Get-PfxCertificate"] = "Get-AlloyedPfxCertificate",
            ["Get-Process"] = "Get-AlloyedProcess",
            ["gps"] = "Get-AlloyedProcess",
            ["ps"] = "Get-AlloyedProcess",
            ["Get-Random"] = "Get-AlloyedRandom",
            ["Get-Service"] = "Get-AlloyedService",
            ["gsv"] = "Get-AlloyedService",
            ["Group-Object"] = "Group-AlloyedObject",
            ["group"] = "Group-AlloyedObject",
            ["Invoke-Command"] = "Invoke-AlloyedCommand",
            ["icm"] = "Invoke-AlloyedCommand",
            ["Join-Path"] = "Join-AlloyedPath",
            ["Measure-Object"] = "Measure-AlloyedObject",
            ["measure"] = "Measure-AlloyedObject",
            ["Move-Item"] = "Move-AlloyedItem",
            ["mi"] = "Move-AlloyedItem",
            ["move"] = "Move-AlloyedItem",
            ["New-Item"] = "New-AlloyedItem",
            ["ni"] = "New-AlloyedItem",
            ["New-SelfSignedCertificate"] = "New-AlloyedSelfSignedCertificate",
            ["Pop-Location"] = "Pop-AlloyedLocation",
            ["popd"] = "Pop-AlloyedLocation",
            ["Push-Location"] = "Push-AlloyedLocation",
            ["pushd"] = "Push-AlloyedLocation",
            ["Read-Host"] = "Read-AlloyedHost",
            ["Remove-Item"] = "Remove-AlloyedItem",
            ["del"] = "Remove-AlloyedItem",
            ["ri"] = "Remove-AlloyedItem",
            ["rm"] = "Remove-AlloyedItem",
            ["Resolve-Path"] = "Resolve-AlloyedPath",
            ["Restart-Service"] = "Restart-AlloyedService",
            ["Select-String"] = "Select-AlloyedString",
            ["sls"] = "Select-AlloyedString",
            ["Set-Acl"] = "Set-AlloyedAcl",
            ["Set-AuthenticodeSignature"] = "Set-AlloyedAuthenticodeSignature",
            ["Set-Content"] = "Set-AlloyedContent",
            ["sc"] = "Set-AlloyedContent",
            ["Set-Location"] = "Set-AlloyedLocation",
            ["cd"] = "Set-AlloyedLocation",
            ["chdir"] = "Set-AlloyedLocation",
            ["sl"] = "Set-AlloyedLocation",
            ["Sort-Object"] = "Sort-AlloyedObject",
            ["sort"] = "Sort-AlloyedObject",
            ["Split-Path"] = "Split-AlloyedPath",
            ["Start-Process"] = "Start-AlloyedProcess",
            ["saps"] = "Start-AlloyedProcess",
            ["start"] = "Start-AlloyedProcess",
            ["Start-Service"] = "Start-AlloyedService",
            ["sasv"] = "Start-AlloyedService",
            ["Stop-Process"] = "Stop-AlloyedProcess",
            ["kill"] = "Stop-AlloyedProcess",
            ["spps"] = "Stop-AlloyedProcess",
            ["Stop-Service"] = "Stop-AlloyedService",
            ["spsv"] = "Stop-AlloyedService",
            ["Test-Connection"] = "Test-AlloyedConnection",
            ["Test-Path"] = "Test-AlloyedPath",
            ["tp"] = "Test-AlloyedPath",
            ["Wait-Process"] = "Wait-AlloyedProcess",
            ["Write-Host"] = "Write-AlloyedHost",
            ["Write-Progress"] = "Write-AlloyedProgress",
// </auto-generated:wrapper-map>
        };

    public bool HasWrapper(string commandName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(commandName);
        return WrapperMap.ContainsKey(commandName);
    }

    public string GetWrapperName(string commandName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(commandName);

        if (!WrapperMap.TryGetValue(commandName, out var wrapperName))
        {
            throw new KeyNotFoundException($"Wrapper mapping was not found for command '{commandName}'.");
        }

        return wrapperName;
    }

    public ResolutionResult Resolve(IEnumerable<string> commands)
    {
        ArgumentNullException.ThrowIfNull(commands);

        var normalized = commands
            .Where(static c => !string.IsNullOrWhiteSpace(c))
            .Select(static c => c.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(static c => c, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var replacements = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var missing = new List<string>();

        foreach (var command in normalized)
        {
            if (WrapperMap.TryGetValue(command, out var wrapper))
            {
                replacements[command] = wrapper;
                continue;
            }

            replacements[command] = command;
            missing.Add(command);
        }

        var requiredModules = GetRequiredModules(normalized);

        return new ResolutionResult(
            Replacements: replacements,
            MissingCommands: missing,
            RequiredModules: requiredModules);
    }

    public IReadOnlyList<string> GetRequiredModules(IEnumerable<string> commands)
    {
        ArgumentNullException.ThrowIfNull(commands);

        var hasMappedCommands = commands.Any(static c =>
            !string.IsNullOrWhiteSpace(c) && WrapperMap.ContainsKey(c.Trim()));

        if (!hasMappedCommands)
        {
            return Array.Empty<string>();
        }

        return new[] { WrapperModuleName };
    }

    public IReadOnlyDictionary<string, string> GetMappings()
    {
        return WrapperMap
            .OrderBy(static kv => kv.Key, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(static kv => kv.Key, static kv => kv.Value, StringComparer.OrdinalIgnoreCase);
    }
}



