@{
    RootModule        = 'GoldenPipelineModule.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '__GUID__'
    Author            = '__AUTHOR__'
    CompanyName       = 'Alloyed'
    Description       = 'Generated by Alloyed transformation pipeline.'
    PowerShellVersion = '7.0'
    CompatiblePSEditions = @('Core')
    RequiredModules   = @('Alloyed.DevOps.Multitool')
    FunctionsToExport = @('*')
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    PrivateData = @{
        PSData = @{
            Tags = @('alloyed', 'devops', 'multitool', 'portable')
        }
    }
}
