namespace Alloyed.DevOps.Multitool.Host.PowerShell.Services;

using Alloyed.DevOps.Multitool.Core.Ast.Contracts;
using Alloyed.DevOps.Multitool.Core.Ast.Models;
using Alloyed.DevOps.Multitool.Core.Builders.Contracts;
using Alloyed.DevOps.Multitool.Core.Builders.Models;
using Alloyed.DevOps.Multitool.Core.Catalog.Contracts;
using Alloyed.DevOps.Multitool.Host.PowerShell.Contracts;
using Alloyed.DevOps.Multitool.Host.PowerShell.Models;

public sealed class TransformationPipeline : ITransformationPipeline
{
    private readonly IScriptAnalyzer _analyzer;
    private readonly IWrapperCatalog _catalog;
    private readonly ICommandTransformer _transformer;
    private readonly IModuleBuilder _moduleBuilder;

    public TransformationPipeline(
        IScriptAnalyzer analyzer,
        IWrapperCatalog catalog,
        ICommandTransformer transformer,
        IModuleBuilder moduleBuilder)
    {
        _analyzer = analyzer;
        _catalog = catalog;
        _transformer = transformer;
        _moduleBuilder = moduleBuilder;
    }

    public PipelineResult Execute(PipelineRequest request)
    {
        try
        {
            Validate(request);

            var modulePath = Path.Combine(request.OutputPath, request.ModuleName);
            if (Directory.Exists(modulePath) && !request.Force)
            {
                var diagnostics = new[]
                {
                    new PipelineDiagnostic(
                        Code: "PIPELINE-OUTPUT-EXISTS",
                        Source: "pipeline",
                        Message: $"Output module already exists: {modulePath}. Use Force=true to overwrite.",
                        Line: 0,
                        Column: 0,
                        Severity: PipelineDiagnosticSeverity.Error),
                };

                return new PipelineResult(
                    Success: false,
                    ModulePath: modulePath,
                    CommandsFound: 0,
                    CommandsReplaced: 0,
                    MissingCommands: Array.Empty<string>(),
                    Diagnostics: diagnostics,
                    ErrorMessage: diagnostics[0].Message);
            }

            var analysis = _analyzer.AnalyzeFile(request.ScriptPath);
            var pipelineDiagnostics = MapAstDiagnostics(analysis.Diagnostics);

            if (request.FailOnSeverity is { } threshold && pipelineDiagnostics.Any(d => d.Severity >= threshold))
            {
                var message = $"Pipeline stopped because analyzer diagnostics met fail policy ({threshold} or higher).";
                var diagnostics = pipelineDiagnostics.Concat(new[]
                {
                    new PipelineDiagnostic(
                        Code: "PIPELINE-FAIL-ON-SEVERITY",
                        Source: "pipeline",
                        Message: message,
                        Line: 0,
                        Column: 0,
                        Severity: PipelineDiagnosticSeverity.Error),
                }).ToArray();

                return new PipelineResult(
                    Success: false,
                    ModulePath: string.Empty,
                    CommandsFound: analysis.Commands.Count,
                    CommandsReplaced: 0,
                    MissingCommands: Array.Empty<string>(),
                    Diagnostics: diagnostics,
                    ErrorMessage: message);
            }

            var commandNames = analysis.Commands.Select(static c => c.CommandName).ToList();
            var resolution = _catalog.Resolve(commandNames);
            var transformed = _transformer.Transform(analysis.SourceText, resolution.Replacements);

            var buildRequest = new ModuleBuildRequest(
                ModuleName: request.ModuleName,
                OutputPath: request.OutputPath,
                TransformedScript: transformed,
                RequiredModules: resolution.RequiredModules,
                Author: Environment.UserName,
                Description: "Generated by Alloyed transformation pipeline.");

            var buildResult = _moduleBuilder.Build(buildRequest);
            if (!buildResult.Success)
            {
                var diagnostics = pipelineDiagnostics.Concat(new[]
                {
                    new PipelineDiagnostic(
                        Code: "MODULE-BUILD-FAILED",
                        Source: "module-builder",
                        Message: buildResult.ErrorMessage ?? "Module build failed.",
                        Line: 0,
                        Column: 0,
                        Severity: PipelineDiagnosticSeverity.Error),
                }).ToArray();

                return new PipelineResult(
                    Success: false,
                    ModulePath: string.Empty,
                    CommandsFound: analysis.Commands.Count,
                    CommandsReplaced: CountReplacements(resolution.Replacements),
                    MissingCommands: resolution.MissingCommands,
                    Diagnostics: diagnostics,
                    ErrorMessage: buildResult.ErrorMessage);
            }

            return new PipelineResult(
                Success: true,
                ModulePath: buildResult.ModulePath,
                CommandsFound: analysis.Commands.Count,
                CommandsReplaced: CountReplacements(resolution.Replacements),
                MissingCommands: resolution.MissingCommands,
                Diagnostics: pipelineDiagnostics,
                ErrorMessage: null);
        }
        catch (Exception ex)
        {
            var diagnostics = new[]
            {
                new PipelineDiagnostic(
                    Code: "PIPELINE-EXCEPTION",
                    Source: "pipeline",
                    Message: ex.Message,
                    Line: 0,
                    Column: 0,
                    Severity: PipelineDiagnosticSeverity.Error),
            };

            return new PipelineResult(
                Success: false,
                ModulePath: string.Empty,
                CommandsFound: 0,
                CommandsReplaced: 0,
                MissingCommands: Array.Empty<string>(),
                Diagnostics: diagnostics,
                ErrorMessage: ex.Message);
        }
    }

    private static void Validate(PipelineRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.ScriptPath);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.ModuleName);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.OutputPath);
    }

    private static int CountReplacements(IReadOnlyDictionary<string, string> replacements)
    {
        return replacements.Count(static kv => !string.Equals(kv.Key, kv.Value, StringComparison.OrdinalIgnoreCase));
    }

    private static PipelineDiagnostic[] MapAstDiagnostics(IReadOnlyList<ParseDiagnostic> diagnostics)
    {
        if (diagnostics.Count == 0)
        {
            return Array.Empty<PipelineDiagnostic>();
        }

        return diagnostics
            .Select(static d => new PipelineDiagnostic(
                Code: InferAstCode(d.Message),
                Source: "ast-analyzer",
                Message: d.Message,
                Line: d.Line,
                Column: d.Column,
                Severity: MapSeverity(d.Severity)))
            .ToArray();
    }

    private static string InferAstCode(string message)
    {
        if (message.Contains("unterminated string", StringComparison.OrdinalIgnoreCase) ||
            message.Contains("missing the terminator", StringComparison.OrdinalIgnoreCase))
        {
            return "AST-UNTERMINATED-STRING";
        }

        if (message.Contains("unbalanced quote", StringComparison.OrdinalIgnoreCase))
        {
            return "AST-UNBALANCED-QUOTE";
        }

        return "AST-DIAGNOSTIC";
    }

    private static PipelineDiagnosticSeverity MapSeverity(ParseDiagnosticSeverity severity)
    {
        return severity switch
        {
            ParseDiagnosticSeverity.Info => PipelineDiagnosticSeverity.Info,
            ParseDiagnosticSeverity.Warning => PipelineDiagnosticSeverity.Warning,
            ParseDiagnosticSeverity.Error => PipelineDiagnosticSeverity.Error,
            _ => PipelineDiagnosticSeverity.Warning,
        };
    }
}
