[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

function Set-SectionContent {
    param(
        [Parameter(Mandatory)] [string]$Path,
        [Parameter(Mandatory)] [string]$StartMarker,
        [Parameter(Mandatory)] [string]$EndMarker,
        [Parameter(Mandatory)] [string[]]$ReplacementLines
    )

    $text = Get-Content -Raw -LiteralPath $Path
    $startIndex = $text.IndexOf($StartMarker, [System.StringComparison]::Ordinal)
    $endIndex = $text.IndexOf($EndMarker, [System.StringComparison]::Ordinal)

    if ($startIndex -lt 0 -or $endIndex -lt 0 -or $endIndex -le $startIndex) {
        throw "Could not locate marker section in '$Path'."
    }

    $lineEnding = if ($text.Contains("`r`n", [System.StringComparison]::Ordinal)) { "`r`n" } else { "`n" }
    $sectionStart = $startIndex + $StartMarker.Length
    $replacement = $lineEnding + (($ReplacementLines -join $lineEnding).TrimEnd()) + $lineEnding
    $updated = $text.Substring(0, $sectionStart) + $replacement + $text.Substring($endIndex)
    $normalized = $updated.TrimEnd("`r", "`n") + $lineEnding

    Set-Content -LiteralPath $Path -Value $normalized -NoNewline
}

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$catalogFile = Join-Path $PSScriptRoot "ports.catalog.json"

if (-not (Test-Path -LiteralPath $catalogFile)) {
    throw "Catalog file not found: $catalogFile"
}

$entries = @(Get-Content -Raw -LiteralPath $catalogFile | ConvertFrom-Json)

if (-not $entries -or $entries.Count -eq 0) {
    throw "Catalog file is empty: $catalogFile"
}

$wrapperLines = New-Object System.Collections.Generic.List[string]
foreach ($entry in ($entries | Sort-Object command)) {
    if ($entry.command -eq "Clear-Host") {
        $wrapperLines.Add(('function {0} {{ Invoke-AlloyedDecoratedCommand -Operation ''{1}'' -Parameters @{{}} -Action {{ {2} }} }}' -f $entry.wrapper, $entry.command, $entry.native))
    }
    else {
        $wrapperLines.Add(('function {0} {{ Invoke-AlloyedDecoratedCommand -Operation ''{1}'' -Arguments $args -InputObjects @($input) -Action {{{2} @args }} }}' -f $entry.wrapper, $entry.command, $entry.native))
    }
}

$modulePath = Join-Path $repoRoot "src/powershell/Public/Ports.Wrappers.ps1"

Set-SectionContent `
    -Path $modulePath `
    -StartMarker "# <auto-generated:wrappers>" `
    -EndMarker "# </auto-generated:wrappers>" `
    -ReplacementLines $wrapperLines

Write-Host "Synced wrappers from catalog: $catalogFile"
