$script:AssemblyLoaded = $false
$script:SessionModeEnabled = $false
$script:SessionModeAliases = @()
$script:SessionModeAliasBackup = @{}
$script:SessionModeCommandBackup = @{}
$script:DecorationPipeline = $null
$script:TransparencyModeOverride = $null
$script:ConsoleOutputModeOverride = $null
$script:LastRuntimeExecution = $null

# Layered command composition: keep public session/runtime orchestration
# decoupled from low-level implementation helpers in this file.
. (Join-Path $PSScriptRoot 'Public/Session.Commands.ps1')
. (Join-Path $PSScriptRoot 'Public/Pipeline.Commands.ps1')
. (Join-Path $PSScriptRoot 'Public/Transparency.Commands.ps1')
. (Join-Path $PSScriptRoot 'Internal/Runtime.Configuration.ps1')
. (Join-Path $PSScriptRoot 'Internal/Session.Interception.ps1')
. (Join-Path $PSScriptRoot 'Internal/Runtime.Execution.ps1')

function Initialize-AlloyedHostAssembly {
    if ($script:AssemblyLoaded) { return }

    $packagedDllPath = Join-Path $PSScriptRoot 'lib/Alloyed.DevOps.Multitool.Host.PowerShell.dll'
    $packagedDecorationDllPath = Join-Path $PSScriptRoot 'lib/Alloyed.DevOps.Multitool.Core.Decoration.dll'

    $moduleRoot = Split-Path -Parent $PSScriptRoot
    $devDllPath = Join-Path $moduleRoot 'dotnet/Alloyed.DevOps.Multitool.Host.PowerShell/bin/Debug/net8.0/Alloyed.DevOps.Multitool.Host.PowerShell.dll'
    $devDecorationDllPath = Join-Path $moduleRoot 'dotnet/Alloyed.DevOps.Multitool.Core.Decoration/bin/Debug/net8.0/Alloyed.DevOps.Multitool.Core.Decoration.dll'

    if ((Test-Path $packagedDllPath) -and (Test-Path $packagedDecorationDllPath)) {
        $dllPath = $packagedDllPath
        $decorationDllPath = $packagedDecorationDllPath
    } else {
        $dllPath = $devDllPath
        $decorationDllPath = $devDecorationDllPath
    }

    if (-not (Test-Path $dllPath)) {
        throw "Host assembly not found at '$dllPath'. Build solution first."
    }
    if (-not (Test-Path $decorationDllPath)) {
        throw "Decoration assembly not found at '$decorationDllPath'. Build solution first."
    }

    Add-Type -Path $decorationDllPath
    Add-Type -Path $dllPath
    $script:AssemblyLoaded = $true
}

function Resolve-FailOnSeverity {
    param(
        [string]$FailOnSeverity,
        [switch]$FailOnWarnings
    )

    if (-not [string]::IsNullOrWhiteSpace($FailOnSeverity)) {
        return [Alloyed.DevOps.Multitool.Host.PowerShell.Models.PipelineDiagnosticSeverity]::$FailOnSeverity
    }

    if ($FailOnWarnings.IsPresent) {
        return [Alloyed.DevOps.Multitool.Host.PowerShell.Models.PipelineDiagnosticSeverity]::Warning
    }

    return $null
}

function Resolve-AlloyedTransparencyEnabled {
    if ($null -ne $script:TransparencyModeOverride) {
        return [bool]$script:TransparencyModeOverride
    }

    $configuration = [Alloyed.DevOps.Multitool.Host.PowerShell.Services.PipelineBootstrap]::CreateRuntimeConfiguration((Get-Location).Path, $null)
    return [bool]$configuration.Decoration.EnableTransparency
}

function Resolve-AlloyedConsoleOutputMode {
    if ($null -ne $script:ConsoleOutputModeOverride) {
        return $script:ConsoleOutputModeOverride
    }

    $environmentMode = [System.Environment]::GetEnvironmentVariable('ALLOYED_CONSOLE_OUTPUT_MODE')
    if (-not [string]::IsNullOrWhiteSpace($environmentMode)) {
        if ($environmentMode -ieq 'rich') {
            return [Alloyed.DevOps.Multitool.Host.PowerShell.Services.ConsoleOutputMode]::Rich
        }
    }

    return [Alloyed.DevOps.Multitool.Host.PowerShell.Services.ConsoleOutputMode]::Plain
}

function Initialize-AlloyedInternalSpectreRuntime {
    [CmdletBinding()]
    param()

    Initialize-AlloyedHostAssembly

    if ($null -ne ('Spectre.Console.AnsiConsole' -as [type])) {
        return
    }

    $hostAssemblyPath = [Alloyed.DevOps.Multitool.Host.PowerShell.Services.PipelineBootstrap].Assembly.Location
    if ([string]::IsNullOrWhiteSpace($hostAssemblyPath)) {
        throw "Unable to resolve Host.PowerShell assembly location for Spectre bootstrap."
    }

    $hostAssemblyDir = Split-Path -Parent $hostAssemblyPath
    $spectreDllPath = Join-Path $hostAssemblyDir 'Spectre.Console.dll'

    if (-not (Test-Path -LiteralPath $spectreDllPath)) {
        throw "Spectre.Console assembly was not found at '$spectreDllPath'. Build host project first: dotnet build src/dotnet/Alloyed.DevOps.Multitool.Host.PowerShell -c Debug"
    }

    Add-Type -Path $spectreDllPath

    if ($null -eq ('Spectre.Console.AnsiConsole' -as [type])) {
        throw "Spectre.Console types are still unavailable after loading '$spectreDllPath'."
    }
}

# ---------------------------------------------------------------------------
# Provider.FileSystem wrappers
# ---------------------------------------------------------------------------

# <auto-generated:wrappers>
function Clear-AlloyedHost { Invoke-AlloyedDecoratedCommand -Operation 'Clear-Host' -Parameters @{} -Action { Microsoft.PowerShell.Core\Clear-Host } }
function Compress-AlloyedArchive { Invoke-AlloyedDecoratedCommand -Operation 'Compress-Archive' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Archive\Compress-Archive @args } }
function ConvertFrom-AlloyedJson { Invoke-AlloyedDecoratedCommand -Operation 'ConvertFrom-Json' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Utility\ConvertFrom-Json @args } }
function ConvertFrom-AlloyedSecureString { Invoke-AlloyedDecoratedCommand -Operation 'ConvertFrom-SecureString' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Security\ConvertFrom-SecureString @args } }
function ConvertTo-AlloyedJson { Invoke-AlloyedDecoratedCommand -Operation 'ConvertTo-Json' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Utility\ConvertTo-Json @args } }
function ConvertTo-AlloyedSecureString { Invoke-AlloyedDecoratedCommand -Operation 'ConvertTo-SecureString' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Security\ConvertTo-SecureString @args } }
function ConvertTo-AlloyedXml { Invoke-AlloyedDecoratedCommand -Operation 'ConvertTo-Xml' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Utility\ConvertTo-Xml @args } }
function Copy-AlloyedItem { Invoke-AlloyedDecoratedCommand -Operation 'Copy-Item' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Copy-Item @args } }
function Expand-AlloyedArchive { Invoke-AlloyedDecoratedCommand -Operation 'Expand-Archive' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Archive\Expand-Archive @args } }
function Export-AlloyedPfxCertificate { Invoke-AlloyedDecoratedCommand -Operation 'Export-PfxCertificate' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Security\Export-PfxCertificate @args } }
function Get-AlloyedAcl { Invoke-AlloyedDecoratedCommand -Operation 'Get-Acl' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Security\Get-Acl @args } }
function Get-AlloyedAuthenticodeSignature { Invoke-AlloyedDecoratedCommand -Operation 'Get-AuthenticodeSignature' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Security\Get-AuthenticodeSignature @args } }
function Get-AlloyedChildItem { Invoke-AlloyedDecoratedCommand -Operation 'Get-ChildItem' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Get-ChildItem @args } }
function Get-AlloyedContent { Invoke-AlloyedDecoratedCommand -Operation 'Get-Content' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Get-Content @args } }
function Get-AlloyedCredential { Invoke-AlloyedDecoratedCommand -Operation 'Get-Credential' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Security\Get-Credential @args } }
function Get-AlloyedItem { Invoke-AlloyedDecoratedCommand -Operation 'Get-Item' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Get-Item @args } }
function Get-AlloyedLocation { Invoke-AlloyedDecoratedCommand -Operation 'Get-Location' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Get-Location @args } }
function Get-AlloyedPfxCertificate { Invoke-AlloyedDecoratedCommand -Operation 'Get-PfxCertificate' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Security\Get-PfxCertificate @args } }
function Get-AlloyedProcess { Invoke-AlloyedDecoratedCommand -Operation 'Get-Process' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Get-Process @args } }
function Get-AlloyedRandom { Invoke-AlloyedDecoratedCommand -Operation 'Get-Random' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Utility\Get-Random @args } }
function Get-AlloyedService { Invoke-AlloyedDecoratedCommand -Operation 'Get-Service' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Get-Service @args } }
function Group-AlloyedObject { Invoke-AlloyedDecoratedCommand -Operation 'Group-Object' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Utility\Group-Object @args } }
function Invoke-AlloyedCommand { Invoke-AlloyedDecoratedCommand -Operation 'Invoke-Command' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Core\Invoke-Command @args } }
function Join-AlloyedPath { Invoke-AlloyedDecoratedCommand -Operation 'Join-Path' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Join-Path @args } }
function Measure-AlloyedObject { Invoke-AlloyedDecoratedCommand -Operation 'Measure-Object' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Utility\Measure-Object @args } }
function Move-AlloyedItem { Invoke-AlloyedDecoratedCommand -Operation 'Move-Item' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Move-Item @args } }
function New-AlloyedItem { Invoke-AlloyedDecoratedCommand -Operation 'New-Item' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\New-Item @args } }
function New-AlloyedSelfSignedCertificate { Invoke-AlloyedDecoratedCommand -Operation 'New-SelfSignedCertificate' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Security\New-SelfSignedCertificate @args } }
function Pop-AlloyedLocation { Invoke-AlloyedDecoratedCommand -Operation 'Pop-Location' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Pop-Location @args } }
function Push-AlloyedLocation { Invoke-AlloyedDecoratedCommand -Operation 'Push-Location' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Push-Location @args } }
function Read-AlloyedHost { Invoke-AlloyedDecoratedCommand -Operation 'Read-Host' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Utility\Read-Host @args } }
function Remove-AlloyedItem { Invoke-AlloyedDecoratedCommand -Operation 'Remove-Item' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Remove-Item @args } }
function Resolve-AlloyedPath { Invoke-AlloyedDecoratedCommand -Operation 'Resolve-Path' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Resolve-Path @args } }
function Restart-AlloyedService { Invoke-AlloyedDecoratedCommand -Operation 'Restart-Service' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Restart-Service @args } }
function Select-AlloyedString { Invoke-AlloyedDecoratedCommand -Operation 'Select-String' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Utility\Select-String @args } }
function Set-AlloyedAcl { Invoke-AlloyedDecoratedCommand -Operation 'Set-Acl' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Security\Set-Acl @args } }
function Set-AlloyedAuthenticodeSignature { Invoke-AlloyedDecoratedCommand -Operation 'Set-AuthenticodeSignature' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Security\Set-AuthenticodeSignature @args } }
function Set-AlloyedContent { Invoke-AlloyedDecoratedCommand -Operation 'Set-Content' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Set-Content @args } }
function Set-AlloyedLocation { Invoke-AlloyedDecoratedCommand -Operation 'Set-Location' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Set-Location @args } }
function Sort-AlloyedObject { Invoke-AlloyedDecoratedCommand -Operation 'Sort-Object' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Utility\Sort-Object @args } }
function Split-AlloyedPath { Invoke-AlloyedDecoratedCommand -Operation 'Split-Path' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Split-Path @args } }
function Start-AlloyedProcess { Invoke-AlloyedDecoratedCommand -Operation 'Start-Process' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Start-Process @args } }
function Start-AlloyedService { Invoke-AlloyedDecoratedCommand -Operation 'Start-Service' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Start-Service @args } }
function Stop-AlloyedProcess { Invoke-AlloyedDecoratedCommand -Operation 'Stop-Process' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Stop-Process @args } }
function Stop-AlloyedService { Invoke-AlloyedDecoratedCommand -Operation 'Stop-Service' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Stop-Service @args } }
function Test-AlloyedConnection { Invoke-AlloyedDecoratedCommand -Operation 'Test-Connection' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Test-Connection @args } }
function Test-AlloyedPath { Invoke-AlloyedDecoratedCommand -Operation 'Test-Path' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Test-Path @args } }
function Wait-AlloyedProcess { Invoke-AlloyedDecoratedCommand -Operation 'Wait-Process' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Management\Wait-Process @args } }
function Write-AlloyedHost { Invoke-AlloyedDecoratedCommand -Operation 'Write-Host' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Utility\Write-Host @args } }
function Write-AlloyedProgress { Invoke-AlloyedDecoratedCommand -Operation 'Write-Progress' -Arguments $args -InputObjects @($input) -Action {Microsoft.PowerShell.Utility\Write-Progress @args } }
# </auto-generated:wrappers>

