@{
    RootModule = 'Alloyed.DevOps.Multitool.psm1'
    ModuleVersion = '0.1.0'
    GUID = '7df0249a-f47f-4f56-a813-7e2ebcdb0b4a'
    Author = 'Alloyed'
    CompanyName = 'Alloyed'
    Copyright = '(c) Alloyed'
    Description = 'PowerShell wrappers for Alloyed transformation pipeline.'
    PowerShellVersion = '7.0'
    CompatiblePSEditions = @('Core')
    FunctionsToExport = @(
        # pipeline cmdlets
        'New-AlloyedModuleTransform',
        'Test-AlloyedTransform',
        'Get-AlloyedCatalog',
        'Get-AlloyedRuntimeConfiguration',
        'Enable-AlloyedSessionMode',
        'Disable-AlloyedSessionMode',
        'Get-AlloyedSessionModeStatus',
        'Enable-AlloyedTransparencyMode',
        'Disable-AlloyedTransparencyMode',
        'Get-AlloyedTransparencyModeStatus',
        # <auto-generated:wrapper-exports>
        'Clear-AlloyedHost',
        'Compress-AlloyedArchive',
        'ConvertFrom-AlloyedJson',
        'ConvertFrom-AlloyedSecureString',
        'ConvertTo-AlloyedJson',
        'ConvertTo-AlloyedSecureString',
        'ConvertTo-AlloyedXml',
        'Copy-AlloyedItem',
        'Expand-AlloyedArchive',
        'Export-AlloyedPfxCertificate',
        'Get-AlloyedAcl',
        'Get-AlloyedAuthenticodeSignature',
        'Get-AlloyedChildItem',
        'Get-AlloyedContent',
        'Get-AlloyedCredential',
        'Get-AlloyedItem',
        'Get-AlloyedLocation',
        'Get-AlloyedPfxCertificate',
        'Get-AlloyedProcess',
        'Get-AlloyedRandom',
        'Get-AlloyedService',
        'Group-AlloyedObject',
        'Invoke-AlloyedCommand',
        'Join-AlloyedPath',
        'Measure-AlloyedObject',
        'Move-AlloyedItem',
        'New-AlloyedItem',
        'New-AlloyedSelfSignedCertificate',
        'Pop-AlloyedLocation',
        'Push-AlloyedLocation',
        'Read-AlloyedHost',
        'Remove-AlloyedItem',
        'Resolve-AlloyedPath',
        'Restart-AlloyedService',
        'Select-AlloyedString',
        'Set-AlloyedAcl',
        'Set-AlloyedAuthenticodeSignature',
        'Set-AlloyedContent',
        'Set-AlloyedLocation',
        'Sort-AlloyedObject',
        'Split-AlloyedPath',
        'Start-AlloyedProcess',
        'Start-AlloyedService',
        'Stop-AlloyedProcess',
        'Stop-AlloyedService',
        'Test-AlloyedConnection',
        'Test-AlloyedPath',
        'Wait-AlloyedProcess',
        'Write-AlloyedHost',
        'Write-AlloyedProgress'
# </auto-generated:wrapper-exports>
    )
    CmdletsToExport = @()
    VariablesToExport = @()
    AliasesToExport = @()
}
