<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\..\tools\ports\ports.catalog.json">
      <LogicalName>Alloyed.DevOps.Multitool.Core.Catalog.Resources.ports.catalog.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
