namespace Alloyed.DevOps.Multitool.Core.Builders.Services;

using System.Text;
using Alloyed.DevOps.Multitool.Core.Builders.Contracts;
using Alloyed.DevOps.Multitool.Core.Builders.Models;

public sealed class MinimalModuleBuilder : IModuleBuilder
{
    public ModuleBuildResult Build(ModuleBuildRequest request)
    {
        try
        {
            Validate(request);

            var moduleDir = Path.Combine(request.OutputPath, request.ModuleName);
            Directory.CreateDirectory(moduleDir);

            var psm1Path = Path.Combine(moduleDir, $"{request.ModuleName}.psm1");
            var psd1Path = Path.Combine(moduleDir, $"{request.ModuleName}.psd1");
            var readmePath = Path.Combine(moduleDir, "README.md");

            File.WriteAllText(psm1Path, request.TransformedScript, Encoding.UTF8);
            File.WriteAllText(psd1Path, BuildManifest(request), Encoding.UTF8);
            File.WriteAllText(readmePath, BuildReadme(request), Encoding.UTF8);

            return new ModuleBuildResult(
                Success: true,
                ModulePath: moduleDir,
                Files: new[] { psm1Path, psd1Path, readmePath },
                ErrorMessage: null);
        }
        catch (Exception ex)
        {
            return new ModuleBuildResult(
                Success: false,
                ModulePath: string.Empty,
                Files: Array.Empty<string>(),
                ErrorMessage: ex.Message);
        }
    }

    private static void Validate(ModuleBuildRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.ModuleName);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.OutputPath);
        ArgumentNullException.ThrowIfNull(request.RequiredModules);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.Author);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.Description);
    }

    private static string BuildManifest(ModuleBuildRequest request)
    {
        var requiredModulesLiteral = request.RequiredModules.Count == 0
            ? "@()"
            : "@(" + string.Join(", ", request.RequiredModules.Select(static m => $"'{m}'")) + ")";

        return $@"@{{
    RootModule        = '{request.ModuleName}.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '{Guid.NewGuid()}'
    Author            = '{EscapeSingleQuotes(request.Author)}'
    CompanyName       = 'Alloyed'
    Description       = '{EscapeSingleQuotes(request.Description)}'
    PowerShellVersion = '7.0'
    CompatiblePSEditions = @('Core')
    RequiredModules   = {requiredModulesLiteral}
    FunctionsToExport = @('*')
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    PrivateData = @{{
        PSData = @{{
            Tags = @('alloyed', 'devops', 'multitool', 'portable')
        }}
    }}
}}";
    }

    private static string BuildReadme(ModuleBuildRequest request)
    {
        return $@"# {request.ModuleName}

{request.Description}

## Generated By
- MinimalModuleBuilder

## Required Modules
{string.Join(Environment.NewLine, request.RequiredModules.Select(static m => $"- {m}"))}
";
    }

    private static string EscapeSingleQuotes(string value)
    {
        return value.Replace("'", "''", StringComparison.Ordinal);
    }
}
